### ISSUE TITLE
Missing ./dataset/chembl.csv

### ISSUE THREAD

**Issue by Youzhuqinghuan** [alhqlearn/REEXPLORE#1]
When I run `python Reaction_A_rl_training.py --agent_dataset ChEMBL --trajectories_method random --num_trajectories 4000`, I found `FileNotFoundError: [Errno 2] No such file or directory: './dataset/chembl.csv'`, how can I get it? Maybe it`s in Git LFS? I never use it before.
Thank you very much for providing the open-source code. I hope you can address my questions. Thanks!

**Comment by alhqlearn** [comment]
Thank you for pointing out that. I have shared all the datasets used at the following link:
https://drive.google.com/drive/folders/1n-MfWsh3Y1d_HflR44dVPX1UbHuRq0BK?usp=sharing
Since the files exceed 25MB, I have provided access via Google Drive.

**Comment by Youzhuqinghuan** [comment]
Got it. Thank you for your sharing!
